# Generated by Django 5.1.4 on 2025-02-10 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0014_alter_alertsettingbondedstatus_template_decraease_and_more'),
        ('users', '0003_alter_userphone_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAlertBondedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider Call ID')),
                ('sent_text', models.TextField(verbose_name='Voice Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Unitalk.cloud)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='Voice Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_bonded_status_voice', to='alerts.alertsettingbondedstatus', verbose_name='Bond Status Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bond Status Voice Alert',
                'verbose_name_plural': 'Bond Status Voice Alerts',
            },
        ),
        migrations.CreateModel(
            name='VoiceAlertComission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider Call ID')),
                ('sent_text', models.TextField(verbose_name='Voice Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Unitalk.cloud)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='Voice Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_comission_voice', to='alerts.alertsettingcomission', verbose_name='Comission Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comission Voice Alert',
                'verbose_name_plural': 'Comission Voice Alerts',
            },
        ),
        migrations.CreateModel(
            name='VoiceAlertJailedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider Call ID')),
                ('sent_text', models.TextField(verbose_name='Voice Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Unitalk.cloud)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='Voice Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_jailed_status_voice', to='alerts.alertsettingjailedstatus', verbose_name='Jailed Alert Setting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Jailed Voice Alert',
                'verbose_name_plural': 'jailed Voice Alerts',
            },
        ),
        migrations.CreateModel(
            name='VoiceAlertTombstonedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider Call ID')),
                ('sent_text', models.TextField(verbose_name='Voice Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Unitalk.cloud)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='Voice Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_tombstoned_status_voice', to='alerts.alertsettingtombstonedstatus', verbose_name='Tombstoned Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tombstoned Voice Alert',
                'verbose_name_plural': 'Tombstoned Voice Alerts',
            },
        ),
        migrations.CreateModel(
            name='VoiceAlertUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider Call ID')),
                ('sent_text', models.TextField(verbose_name='Voice Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Unitalk.cloud)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='Voice Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_uptime_voice', to='alerts.alertsettinguptime', verbose_name='Uptime Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Uptime Voice Alert',
                'verbose_name_plural': 'Uptime Voice Alerts',
            },
        ),
        migrations.CreateModel(
            name='VoiceAlertVotingPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider Call ID')),
                ('sent_text', models.TextField(verbose_name='Voice Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Unitalk.cloud)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='Voice Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_voting_power_voice', to='alerts.alertsettingvotingpower', verbose_name='Voting Power Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Voting Power Voice Alert',
                'verbose_name_plural': 'Voting Power Voice Alerts',
            },
        ),
    ]
