# Generated by Django 5.1.4 on 2025-02-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_alter_voicealertbondedstatus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicealertbondedstatus',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('STARTING', 'starting'), ('RINGING', 'Ringing'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Сompleted'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='voicealertcomission',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('STARTING', 'starting'), ('RINGING', 'Ringing'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Сompleted'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='voicealertjailedstatus',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('STARTING', 'starting'), ('RINGING', 'Ringing'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Сompleted'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='voicealerttombstonedstatus',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('STARTING', 'starting'), ('RINGING', 'Ringing'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Сompleted'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='voicealertuptime',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('STARTING', 'starting'), ('RINGING', 'Ringing'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Сompleted'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='voicealertvotingpower',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('STARTING', 'starting'), ('RINGING', 'Ringing'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Сompleted'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status'),
        ),
    ]
