# Generated by Django 5.1.4 on 2025-02-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_alter_voicealertbondedstatus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicealertbondedstatus',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='voicealertcomission',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='voicealertjailedstatus',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='voicealerttombstonedstatus',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='voicealertuptime',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='voicealertvotingpower',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
    ]
