# Generated by Django 5.1.4 on 2025-02-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0017_alertsettingotelupdate_alertsettingsyncstatus_and_more'),
        ('users', '0003_alter_userphone_phone'),
        ('voice', '0004_voicealertbondedstatus_is_resent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAlertOtelUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider Call ID')),
                ('sent_text', models.TextField(verbose_name='Voice Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Unitalk.cloud)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='Voice Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('STARTING', 'starting'), ('RINGING', 'Ringing'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Сompleted'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('is_resent', models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_otel_update_voice', to='alerts.alertsettingotelupdate', verbose_name='Otel Update Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Otel Update Voice Alert',
                'verbose_name_plural': 'Otel Update Voice Alerts',
            },
        ),
        migrations.CreateModel(
            name='VoiceAlertSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider Call ID')),
                ('sent_text', models.TextField(verbose_name='Voice Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Unitalk.cloud)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='Voice Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('STARTING', 'starting'), ('RINGING', 'Ringing'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Сompleted'), ('NO_ANSWER', 'No answer'), ('BUSY', 'Busy'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('is_resent', models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_sync_status_voice', to='alerts.alertsettingsyncstatus', verbose_name='Sync Status Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sync Status Voice Alert',
                'verbose_name_plural': 'Sync Status Voice Alerts',
            },
        ),
    ]
