# Generated by Django 5.1.4 on 2025-03-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0022_alter_blockchain_ntype'),
        ('voice', '0006_voicephonetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicealertbondedstatus',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicealertbondedstatus',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='voicealertcomission',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicealertcomission',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='voicealertjailedstatus',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicealertjailedstatus',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='voicealertotelupdate',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicealertotelupdate',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='voicealertsyncstatus',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicealertsyncstatus',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='voicealerttombstonedstatus',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicealerttombstonedstatus',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='voicealertuptime',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicealertuptime',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='voicealertvotingpower',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicealertvotingpower',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='voicephonetest',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='voicephonetest',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
    ]
