export enum EBlockchainType {
  COSMOS = "COSMOS",
}

export enum EBlockchainValidatorStatus {
  BOND_STATUS_UNSPECIFIED = "BOND_STATUS_UNSPECIFIED",
  BOND_STATUS_BONDED = "BOND_STATUS_BONDED",
  BOND_STATUS_UNBONDED = "BOND_STATUS_UNBONDED",
  BOND_STATUS_UNBONDING = "BOND_STATUS_UNBONDING",
}
