# Generated by Django 5.1.4 on 2025-02-05 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfirmEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_alert_setting_id', models.IntegerField(verbose_name='User Alert Setting ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Email Subject')),
                ('email_html', models.TextField(verbose_name='Email content')),
                ('code', models.CharField(db_index=True, max_length=255, verbose_name='Confirmation code')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('ERROR', 'Error')], default='NEW', max_length=25, verbose_name='Sending Status')),
                ('err', models.TextField(blank=True, null=True, verbose_name='Error Details')),
                ('expire_code', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Code expiration date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alert_confirm_emails', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Voting Power Alert Settings',
                'verbose_name_plural': 'Voting Power Alerts Settings',
            },
        ),
    ]
