# Generated by Django 5.1.4 on 2025-02-05 20:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_alertconfirmemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertconfirmemail',
            options={'verbose_name': 'Alert Confirm Email', 'verbose_name_plural': 'Alert Confirm Emails'},
        ),
        migrations.AlterField(
            model_name='alertconfirmemail',
            name='email_html',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Email content'),
        ),
    ]
