# Generated by Django 5.1.4 on 2025-02-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_alter_alertconfirmemail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfirmemail',
            name='user_alert_setting_id',
            field=models.IntegerField(db_index=True, verbose_name='User Alert Setting ID'),
        ),
    ]
