# Generated by Django 5.1.4 on 2025-02-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_alter_alertconfirmemail_user_alert_setting_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertConfirmEmail',
        ),
    ]
