# Generated by Django 5.1.4 on 2025-01-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btype', models.SlugField(choices=[('cosmos', 'Cosmos')], default='cosmos', verbose_name='Type')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Blockchain',
                'verbose_name_plural': 'Blockchains',
            },
        ),
        migrations.CreateModel(
            name='BlockchainUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='API URL')),
                ('priority', models.PositiveIntegerField(db_index=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_urls', to='blockchains.blockchain', verbose_name='Blockchain')),
            ],
            options={
                'verbose_name': 'Blockchain URL',
                'verbose_name_plural': 'Blockchain URLs',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_address', models.CharField(db_index=True, max_length=255, verbose_name='Operator Address')),
                ('moniker', models.CharField(db_index=True, max_length=255, verbose_name='Moniker')),
                ('identity', models.CharField(blank=True, max_length=256, null=True, verbose_name='Identity')),
                ('website', models.CharField(blank=True, max_length=256, null=True, verbose_name='Website')),
                ('contact', models.CharField(blank=True, max_length=256, null=True, verbose_name='Security Contact')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_validators', to='blockchains.blockchain', verbose_name='Blockchain')),
            ],
            options={
                'verbose_name': 'Blockchain Validator',
                'verbose_name_plural': 'Blockchain Validators',
            },
        ),
    ]
