# Generated by Django 5.1.4 on 2025-01-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainvalidator',
            name='status',
        ),
    ]
