# Generated by Django 5.1.4 on 2025-01-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0002_remove_blockchainvalidator_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainurl',
            name='url',
        ),
        migrations.AddField(
            model_name='blockchainurl',
            name='infos_url',
            field=models.URLField(default='', verbose_name='Signing Infos URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchainurl',
            name='rpc_url',
            field=models.URLField(default='', verbose_name='RPC URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchainurl',
            name='validators_url',
            field=models.URLField(default='', verbose_name='Validators URL'),
            preserve_default=False,
        ),
    ]
