# Generated by Django 5.1.4 on 2025-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0003_remove_blockchainurl_url_blockchainurl_infos_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainurl',
            name='total_called',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Number of launches'),
            preserve_default=False,
        ),
    ]
