# Generated by Django 5.1.4 on 2025-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0004_blockchainurl_total_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainurl',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Domain Name'),
        ),
    ]
