# Generated by Django 5.1.4 on 2025-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0006_alter_blockchain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainvalidator',
            name='status',
            field=models.SlugField(choices=[('BOND_STATUS_BONDED', 'BOND_STATUS_BONDED'), ('BOND_STATUS_UNBONDED', 'BOND_STATUS_UNBONDED')], default='BOND_STATUS_BONDED', max_length=25),
        ),
    ]
