# Generated by Django 5.1.4 on 2025-01-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0008_blockchainvalidator_jailed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainvalidator',
            name='commision_max_change_rate',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchainvalidator',
            name='commision_max_rate',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchainvalidator',
            name='commision_rate',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchainvalidator',
            name='hex_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HEX Address'),
        ),
        migrations.AddField(
            model_name='blockchainvalidator',
            name='missed_blocks_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchainvalidator',
            name='tombstoned',
            field=models.BooleanField(default=False, verbose_name='Tombstoned status'),
        ),
        migrations.AddField(
            model_name='blockchainvalidator',
            name='valcons_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valcons Address'),
        ),
        migrations.AddField(
            model_name='blockchainvalidator',
            name='voting_power',
            field=models.IntegerField(default=0, verbose_name='Voting Power'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchainvalidator',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet Address'),
        ),
        migrations.AlterField(
            model_name='blockchainvalidator',
            name='jailed',
            field=models.BooleanField(default=False, verbose_name='Jailed'),
        ),
        migrations.AlterField(
            model_name='blockchainvalidator',
            name='moniker',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Moniker'),
        ),
        migrations.AlterField(
            model_name='blockchainvalidator',
            name='status',
            field=models.SlugField(choices=[('BOND_STATUS_UNSPECIFIED', 'BOND_STATUS_UNSPECIFIED'), ('BOND_STATUS_BONDED', 'BOND_STATUS_BONDED'), ('BOND_STATUS_UNBONDED', 'BOND_STATUS_UNBONDED'), ('BOND_STATUS_UNBONDING', 'BOND_STATUS_UNBONDING')], default='BOND_STATUS_BONDED', max_length=25, verbose_name='Status'),
        ),
    ]
