# Generated by Django 5.1.4 on 2025-01-17 15:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0009_blockchainvalidator_commision_max_change_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainvalidator',
            name='uptime',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5),
        ),
    ]
