# Generated by Django 5.1.4 on 2025-01-17 16:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0010_blockchainvalidator_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainvalidator',
            name='uptime',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Uptime, %'),
        ),
    ]
