# Generated by Django 5.1.4 on 2025-01-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0011_alter_blockchainvalidator_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainvalidator',
            name='picture',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Picture'),
        ),
    ]
