# Generated by Django 5.1.4 on 2025-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0012_blockchainvalidator_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainvalidator',
            name='voting_power',
            field=models.IntegerField(db_index=True, verbose_name='Voting Power'),
        ),
    ]
