# Generated by Django 5.1.4 on 2025-02-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0013_alter_blockchainvalidator_voting_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchainurl',
            name='total_called',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='name',
            field=models.CharField(default='Celestia Mainnet', max_length=256, verbose_name='Blockchain Name'),
        ),
    ]
