# Generated by Django 5.1.4 on 2025-02-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0014_remove_blockchainurl_total_called_blockchain_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchainurl',
            options={'ordering': ['priority'], 'verbose_name': 'Blockchain Validator URL', 'verbose_name_plural': 'Blockchain Validator URLs'},
        ),
        migrations.RemoveField(
            model_name='blockchainurl',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='da_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='DA API URL'),
        ),
        migrations.CreateModel(
            name='BlockchainBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=255, verbose_name='Node ID')),
                ('version', models.CharField(max_length=255, verbose_name='Version')),
                ('system_version', models.CharField(max_length=255, verbose_name='System Version')),
                ('node_height', models.IntegerField(db_index=True, verbose_name='Current Node Height')),
                ('last_timestamp', models.BigIntegerField(db_index=True, default=0, verbose_name='Last timestamp pfb total')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_bridges', to='blockchains.blockchain', verbose_name='Blockchain')),
            ],
            options={
                'verbose_name': 'Blockchain Bridge',
                'verbose_name_plural': 'Blockchain Bridges',
            },
        ),
    ]
