# Generated by Django 5.1.4 on 2025-02-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0015_alter_blockchainurl_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='da_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='DA API URL'),
        ),
    ]
