# Generated by Django 5.1.4 on 2025-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0015_alter_blockchainurl_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='network_height',
            field=models.BigIntegerField(default=0, verbose_name='Network Height'),
        ),
    ]
