# Generated by Django 5.1.4 on 2025-02-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0016_blockchain_da_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainbridge',
            name='last_timestamp',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='Last timestamp pfb total'),
        ),
        migrations.AlterField(
            model_name='blockchainbridge',
            name='node_height',
            field=models.IntegerField(verbose_name='Current Node Height'),
        ),
    ]
