# Generated by Django 5.1.4 on 2025-02-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0016_blockchain_network_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='da_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='DA Metrics URL'),
        ),
    ]
