# Generated by Django 5.1.4 on 2025-02-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0017_alter_blockchain_da_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainbridge',
            name='last_timestamp_diff',
            field=models.PositiveIntegerField(default=0, verbose_name='Last timestamp diff (seconds)'),
        ),
        migrations.AddField(
            model_name='blockchainbridge',
            name='node_height_diff',
            field=models.PositiveIntegerField(default=0, verbose_name='The diff between Network height'),
            preserve_default=False,
        ),
    ]
