# Generated by Django 5.1.4 on 2025-02-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0018_blockchainbridge_last_timestamp_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainbridge',
            name='last_timestamp',
            field=models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='Last timestamp pfb total'),
        ),
        migrations.AlterField(
            model_name='blockchainbridge',
            name='last_timestamp_diff',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Last timestamp diff (seconds)'),
        ),
        migrations.AlterField(
            model_name='blockchainbridge',
            name='node_height',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='Current Node Height'),
        ),
        migrations.AlterField(
            model_name='blockchainbridge',
            name='node_height_diff',
            field=models.PositiveBigIntegerField(verbose_name='The diff between Network height'),
        ),
    ]
