# Generated by Django 5.1.4 on 2025-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0019_alter_blockchainbridge_last_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainbridge',
            name='node_height_diff',
            field=models.PositiveBigIntegerField(default=0, verbose_name='The diff between Network height'),
        ),
    ]
