# Generated by Django 5.1.4 on 2025-02-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0020_alter_blockchainbridge_node_height_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='ntype',
            field=models.SlugField(choices=[('CELESTIA_TESTNET', 'Celestia Testnet'), ('CELESTIA_MAINNET', 'Celestia Mainnet')], default='CELESTIA_TESTNET', verbose_name='Network Type'),
        ),
    ]
