# Generated by Django 5.1.4 on 2025-03-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0021_blockchain_ntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='ntype',
            field=models.SlugField(choices=[('CELESTIA_TESTNET', 'Celestia Testnet'), ('CELESTIA_MAINNET', 'Celestia Mainnet'), ('OG_TESTNET', '0g Testnet'), ('OG_MAINNET', '0g Mainnet')], default='CELESTIA_TESTNET', verbose_name='Network Type'),
        ),
    ]
