# Generated by Django 5.1.4 on 2025-04-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0022_alter_blockchain_ntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='ntype',
            field=models.SlugField(choices=[('CELESTIA_TESTNET', 'Celestia Testnet'), ('CELESTIA_MAINNET', 'Celestia Mainnet'), ('OG_TESTNET', '0g Testnet'), ('OG_MAINNET', '0g Mainnet'), ('XRPL_TESTNET', 'XRP Ledger Testnet'), ('XRPL_MAINNET', 'XRP Ledger Mainnet')], default='CELESTIA_TESTNET', verbose_name='Network Type'),
        ),
    ]
