# Generated by Django 5.1.4 on 2025-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0024_alter_blockchain_ntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainvalidator',
            name='voting_power',
            field=models.BigIntegerField(db_index=True, verbose_name='Voting Power'),
        ),
    ]
