# Generated by Django 5.1.4 on 2025-09-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0025_alter_blockchainvalidator_voting_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='ntype',
            field=models.SlugField(choices=[('CELESTIA_TESTNET', 'Celestia Testnet'), ('CELESTIA_MAINNET', 'Celestia Mainnet'), ('OG_TESTNET', '0g Testnet'), ('OG_MAINNET', '0g Mainnet'), ('XRPL_TESTNET', 'XRP Ledger Testnet'), ('XRPL_MAINNET', 'XRP Ledger Mainnet'), ('STORY_TESTNET', 'Story Testnet'), ('STORY_MAINNET', 'Story Mainnet'), ('ALTHEA_TESTNET', 'Althea Testnet'), ('ALTHEA_MAINNET', 'Althea Mainnet'), ('PROVENANCE_TESTNET', 'Provenance Testnet'), ('PROVENANCE_MAINNET', 'Provenance Mainnet'), ('HAQQ_TESTNET', 'Haqq Testnet'), ('HAQQ_MAINNET', 'Haqq Mainnet')], default='CELESTIA_TESTNET', verbose_name='Network Type'),
        ),
    ]
