# Generated by Django 5.1.4 on 2025-02-01 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsettingcomission',
            options={'ordering': ('value_from',), 'verbose_name': 'Comission Alert Settings', 'verbose_name_plural': 'Comission Alerts Settings'},
        ),
        migrations.AlterModelOptions(
            name='alertsettinguptime',
            options={'ordering': ('value_from',), 'verbose_name': 'Uptime Alert Settings', 'verbose_name_plural': 'Uptime Alerts Settings'},
        ),
        migrations.AlterModelOptions(
            name='alertsettingvotingpower',
            options={'ordering': ('value_from',), 'verbose_name': 'Voting Power Alert Settings', 'verbose_name_plural': 'Voting Power Alerts Settings'},
        ),
        migrations.RemoveField(
            model_name='alertsettingcomission',
            name='value',
        ),
        migrations.RemoveField(
            model_name='alertsettinguptime',
            name='value',
        ),
        migrations.RemoveField(
            model_name='alertsettingvotingpower',
            name='value',
        ),
        migrations.AddField(
            model_name='alertsettingcomission',
            name='value_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Value from, %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingcomission',
            name='value_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Value to, %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettinguptime',
            name='value_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Value from, %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettinguptime',
            name='value_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Value to, %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingvotingpower',
            name='value_from',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(5000000)], verbose_name='Value from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingvotingpower',
            name='value_to',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(5000000)], verbose_name='Value to'),
            preserve_default=False,
        ),
    ]
