# Generated by Django 5.1.4 on 2025-02-01 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alertsettingvotingpower_value_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettingcomission',
            name='value_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Value to, %'),
        ),
        migrations.AlterField(
            model_name='alertsettinguptime',
            name='value_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Value to, %'),
        ),
    ]
