# Generated by Django 5.1.4 on 2025-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alertsettingcomission_value_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralertsettingcomission',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useralertsettingjailedstatus',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useralertsettingtombstonedstatus',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useralertsettinguptime',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useralertsettingvotingpower',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
