# Generated by Django 5.1.4 on 2025-02-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_useralertsettingcomission_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralertsettingcomission',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='useralertsettingjailedstatus',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='useralertsettingtombstonedstatus',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='useralertsettinguptime',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='useralertsettingvotingpower',
            name='is_confirmed',
        ),
    ]
