# Generated by Django 5.1.4 on 2025-02-07 00:23

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_remove_useralertsettingcomission_is_confirmed_and_more'),
        ('blockchains', '0014_remove_blockchainurl_total_called_blockchain_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettingBondedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', multiselectfield.db.fields.MultiSelectField(choices=[('SMS', 'SMS'), ('VOICE', 'Voice')], max_length=10, verbose_name='Alert Channels')),
                ('template_increase', models.TextField(verbose_name='Text Template for increase')),
                ('template_decraease', models.TextField(verbose_name='Text Template for decrease')),
                ('status', models.BooleanField(default=True, verbose_name='Enabled')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('true_to_false', models.BooleanField(default=True)),
                ('false_to_true', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bonded Status Alert Settings',
                'verbose_name_plural': 'Bonded Status Alerts Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='alertsettingcomission',
            options={'ordering': ('value',), 'verbose_name': 'Comission Alert Settings', 'verbose_name_plural': 'Comission Alerts Settings'},
        ),
        migrations.AlterModelOptions(
            name='alertsettinguptime',
            options={'ordering': ('value',), 'verbose_name': 'Uptime Alert Settings', 'verbose_name_plural': 'Uptime Alerts Settings'},
        ),
        migrations.AlterModelOptions(
            name='alertsettingvotingpower',
            options={'ordering': ('value',), 'verbose_name': 'Voting Power Alert Settings', 'verbose_name_plural': 'Voting Power Alerts Settings'},
        ),
        migrations.RemoveField(
            model_name='alertsettingcomission',
            name='sms_template',
        ),
        migrations.RemoveField(
            model_name='alertsettingcomission',
            name='value_from',
        ),
        migrations.RemoveField(
            model_name='alertsettingcomission',
            name='value_to',
        ),
        migrations.RemoveField(
            model_name='alertsettingcomission',
            name='voice_template',
        ),
        migrations.RemoveField(
            model_name='alertsettingjailedstatus',
            name='sms_template',
        ),
        migrations.RemoveField(
            model_name='alertsettingjailedstatus',
            name='voice_template',
        ),
        migrations.RemoveField(
            model_name='alertsettingtombstonedstatus',
            name='sms_template',
        ),
        migrations.RemoveField(
            model_name='alertsettingtombstonedstatus',
            name='voice_template',
        ),
        migrations.RemoveField(
            model_name='alertsettinguptime',
            name='sms_template',
        ),
        migrations.RemoveField(
            model_name='alertsettinguptime',
            name='value_from',
        ),
        migrations.RemoveField(
            model_name='alertsettinguptime',
            name='value_to',
        ),
        migrations.RemoveField(
            model_name='alertsettinguptime',
            name='voice_template',
        ),
        migrations.RemoveField(
            model_name='alertsettingvotingpower',
            name='sms_template',
        ),
        migrations.RemoveField(
            model_name='alertsettingvotingpower',
            name='value_from',
        ),
        migrations.RemoveField(
            model_name='alertsettingvotingpower',
            name='value_to',
        ),
        migrations.RemoveField(
            model_name='alertsettingvotingpower',
            name='voice_template',
        ),
        migrations.AddField(
            model_name='alertsettingcomission',
            name='template_decraease',
            field=models.TextField(default='', verbose_name='Text Template for decrease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingcomission',
            name='template_increase',
            field=models.TextField(default='', verbose_name='Text Template for increase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingcomission',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive number to increase, negative to decrease', max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Value, %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingjailedstatus',
            name='template_decraease',
            field=models.TextField(default='', verbose_name='Text Template for decrease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingjailedstatus',
            name='template_increase',
            field=models.TextField(default='', verbose_name='Text Template for increase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingtombstonedstatus',
            name='template_decraease',
            field=models.TextField(default='', verbose_name='Text Template for decrease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingtombstonedstatus',
            name='template_increase',
            field=models.TextField(default='', verbose_name='Text Template for increase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettinguptime',
            name='template_decraease',
            field=models.TextField(default='', verbose_name='Text Template for decrease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettinguptime',
            name='template_increase',
            field=models.TextField(default='', verbose_name='Text Template for increase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettinguptime',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positive number to increase, negative to decrease', max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Value, %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingvotingpower',
            name='template_decraease',
            field=models.TextField(default='', verbose_name='Text Template for decrease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingvotingpower',
            name='template_increase',
            field=models.TextField(default='', verbose_name='Text Template for increase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertsettingvotingpower',
            name='value',
            field=models.IntegerField(default=0, help_text='Positive number to increase, negative to decrease', validators=[django.core.validators.MinValueValidator(-5000000), django.core.validators.MaxValueValidator(5000000)], verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useralertsettingcomission',
            unique_together={('user', 'blockchain_validator', 'setting')},
        ),
        migrations.AlterUniqueTogether(
            name='useralertsettingjailedstatus',
            unique_together={('user', 'blockchain_validator', 'setting')},
        ),
        migrations.AlterUniqueTogether(
            name='useralertsettingtombstonedstatus',
            unique_together={('user', 'blockchain_validator', 'setting')},
        ),
        migrations.AlterUniqueTogether(
            name='useralertsettinguptime',
            unique_together={('user', 'blockchain_validator', 'setting')},
        ),
        migrations.AlterUniqueTogether(
            name='useralertsettingvotingpower',
            unique_together={('user', 'blockchain_validator', 'setting')},
        ),
        migrations.CreateModel(
            name='UserAlertSettingBondedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Enabled')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('channels', models.SlugField(choices=[('SMS', 'SMS'), ('VOICE', 'Voice')], max_length=10, verbose_name='Alert Channel')),
                ('current_value', models.BooleanField(default=False)),
                ('blockchain_validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_validator_user_alert_settings_bonded_status', to='blockchains.blockchainvalidator', verbose_name='Validator')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_setting_bonded_status_user_settings', to='alerts.alertsettingbondedstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alert_settings_bonded_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Alert Setting Bonded Status',
                'verbose_name_plural': 'User Alert Settings Bonded Status',
                'unique_together': {('user', 'blockchain_validator', 'setting')},
            },
        ),
    ]
