# Generated by Django 5.1.4 on 2025-02-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alter_alertsettingbondedstatus_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralertsettingbondedstatus',
            name='next_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useralertsettingcomission',
            name='next_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Next Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useralertsettingjailedstatus',
            name='next_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useralertsettingtombstonedstatus',
            name='next_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useralertsettinguptime',
            name='next_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Next Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useralertsettingvotingpower',
            name='next_value',
            field=models.IntegerField(default=0, verbose_name='Next Value'),
            preserve_default=False,
        ),
    ]
