# Generated by Django 5.1.4 on 2025-02-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_useralertsettingbondedstatus_next_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertsettingbondedstatus',
            name='false_to_true',
        ),
        migrations.RemoveField(
            model_name='alertsettingbondedstatus',
            name='true_to_false',
        ),
        migrations.RemoveField(
            model_name='alertsettingjailedstatus',
            name='false_to_true',
        ),
        migrations.RemoveField(
            model_name='alertsettingjailedstatus',
            name='true_to_false',
        ),
        migrations.RemoveField(
            model_name='alertsettingtombstonedstatus',
            name='false_to_true',
        ),
        migrations.AddField(
            model_name='alertsettingbondedstatus',
            name='value',
            field=models.CharField(choices=[('FALSE_TO_TRUE', 'False to True'), ('TRUE_TO_FALSE', 'True to False')], default='FALSE_TO_TRUE', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='alertsettingjailedstatus',
            name='value',
            field=models.CharField(choices=[('FALSE_TO_TRUE', 'False to True'), ('TRUE_TO_FALSE', 'True to False')], default='FALSE_TO_TRUE', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='alertsettingtombstonedstatus',
            name='value',
            field=models.CharField(choices=[('FALSE_TO_TRUE', 'False to True'), ('TRUE_TO_FALSE', 'True to False')], default='FALSE_TO_TRUE', max_length=25, unique=True),
        ),
    ]
