# Generated by Django 5.1.4 on 2025-02-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_remove_alertsettingbondedstatus_false_to_true_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsettingbondedstatus',
            options={'verbose_name': 'Bond Status Alert Settings', 'verbose_name_plural': 'Bond Status Alerts Settings'},
        ),
        migrations.AlterModelOptions(
            name='useralertsettingbondedstatus',
            options={'verbose_name': 'User Alert Setting Bond Status', 'verbose_name_plural': 'User Alert Settings Bond Status'},
        ),
    ]
