# Generated by Django 5.1.4 on 2025-02-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alter_alertsettingbondedstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralertsettingbondedstatus',
            name='next_value',
        ),
        migrations.RemoveField(
            model_name='useralertsettingcomission',
            name='next_value',
        ),
        migrations.RemoveField(
            model_name='useralertsettingjailedstatus',
            name='next_value',
        ),
        migrations.RemoveField(
            model_name='useralertsettingtombstonedstatus',
            name='next_value',
        ),
        migrations.RemoveField(
            model_name='useralertsettinguptime',
            name='next_value',
        ),
        migrations.RemoveField(
            model_name='useralertsettingvotingpower',
            name='next_value',
        ),
    ]
