# Generated by Django 5.1.4 on 2025-02-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_remove_useralertsettingbondedstatus_next_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralertsettingbondedstatus',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='useralertsettingjailedstatus',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='useralertsettingtombstonedstatus',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='useralertsettinguptime',
            name='current_value',
        ),
    ]
