# Generated by Django 5.1.4 on 2025-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_remove_useralertsettingbondedstatus_current_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettingbondedstatus',
            name='template_decraease',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for decrease (True to False)'),
        ),
        migrations.AlterField(
            model_name='alertsettingbondedstatus',
            name='template_increase',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for increase (False to True)'),
        ),
        migrations.AlterField(
            model_name='alertsettingcomission',
            name='template_decraease',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for decrease (True to False)'),
        ),
        migrations.AlterField(
            model_name='alertsettingcomission',
            name='template_increase',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for increase (False to True)'),
        ),
        migrations.AlterField(
            model_name='alertsettingjailedstatus',
            name='template_decraease',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for decrease (True to False)'),
        ),
        migrations.AlterField(
            model_name='alertsettingjailedstatus',
            name='template_increase',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for increase (False to True)'),
        ),
        migrations.AlterField(
            model_name='alertsettingtombstonedstatus',
            name='template_decraease',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for decrease (True to False)'),
        ),
        migrations.AlterField(
            model_name='alertsettingtombstonedstatus',
            name='template_increase',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for increase (False to True)'),
        ),
        migrations.AlterField(
            model_name='alertsettinguptime',
            name='template_decraease',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for decrease (True to False)'),
        ),
        migrations.AlterField(
            model_name='alertsettinguptime',
            name='template_increase',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for increase (False to True)'),
        ),
        migrations.AlterField(
            model_name='alertsettingvotingpower',
            name='template_decraease',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for decrease (True to False)'),
        ),
        migrations.AlterField(
            model_name='alertsettingvotingpower',
            name='template_increase',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template for increase (False to True)'),
        ),
    ]
