# Generated by Django 5.1.4 on 2025-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alter_alertsettingbondedstatus_template_decraease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsettingbondedstatus',
            name='template',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template'),
        ),
        migrations.AddField(
            model_name='alertsettingcomission',
            name='template',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template'),
        ),
        migrations.AddField(
            model_name='alertsettingjailedstatus',
            name='template',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template'),
        ),
        migrations.AddField(
            model_name='alertsettingtombstonedstatus',
            name='template',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template'),
        ),
        migrations.AddField(
            model_name='alertsettinguptime',
            name='template',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template'),
        ),
        migrations.AddField(
            model_name='alertsettingvotingpower',
            name='template',
            field=models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template'),
        ),
    ]
