# Generated by Django 5.1.4 on 2025-02-18 11:08

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_remove_alertsettingbondedstatus_template_decraease_and_more'),
        ('blockchains', '0020_alter_blockchainbridge_node_height_diff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettingOtelUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SMS', 'SMS'), ('VOICE', 'Voice')], max_length=10, null=True, verbose_name='Alert Channels')),
                ('template', models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template')),
                ('status', models.BooleanField(default=True, verbose_name='Enabled')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('value', models.IntegerField(help_text='Number of seconds', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(600)], verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Otel Update Alert Settings',
                'verbose_name_plural': 'Otel Update Alerts Settings',
            },
        ),
        migrations.CreateModel(
            name='AlertSettingSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SMS', 'SMS'), ('VOICE', 'Voice')], max_length=10, null=True, verbose_name='Alert Channels')),
                ('template', models.TextField(blank=True, help_text='\n{name} - will be replaced to full name;<br>\n{network} - will be replaced to blockchain network (Celestia Mainnet);<br>\n{moniker} - will be replaced to validator moniker;<br>\n{from_value} - will be replaced to from value (int, float or bool);<br>\n{to_value} - will be replaced to from value (int, float or bool);<br>\n', null=True, verbose_name='Text Template')),
                ('status', models.BooleanField(default=True, verbose_name='Enabled')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('value', models.IntegerField(help_text='Positive number to increase, negative to decrease', validators=[django.core.validators.MinValueValidator(-10000), django.core.validators.MaxValueValidator(10000)], verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Sync Status Alert Settings',
                'verbose_name_plural': 'Sync Status Alerts Settings',
            },
        ),
        migrations.CreateModel(
            name='UserAlertSettingOtelUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Enabled')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('channels', models.SlugField(choices=[('SMS', 'SMS'), ('VOICE', 'Voice')], max_length=10, verbose_name='Alert Channel')),
                ('current_value', models.IntegerField(verbose_name='Current Value')),
                ('blockchain_validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_validator_user_alert_settings_otel_update', to='blockchains.blockchainbridge', verbose_name='Bridge')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_setting_otel_update_user_settings', to='alerts.alertsettingotelupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alert_settings_otel_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Alert Setting Otel Update',
                'verbose_name_plural': 'User Alert Settings Otel Update',
                'unique_together': {('user', 'blockchain_validator', 'setting')},
            },
        ),
        migrations.CreateModel(
            name='UserAlertSettingSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Enabled')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('channels', models.SlugField(choices=[('SMS', 'SMS'), ('VOICE', 'Voice')], max_length=10, verbose_name='Alert Channel')),
                ('current_value', models.IntegerField(verbose_name='Current Value')),
                ('blockchain_validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_validator_user_alert_settings_sync_status', to='blockchains.blockchainbridge', verbose_name='Bridge')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_setting_sync_status_user_settings', to='alerts.alertsettingsyncstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alert_settings_sync_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Alert Setting Sync Status',
                'verbose_name_plural': 'User Alert Settings Sync Status',
                'unique_together': {('user', 'blockchain_validator', 'setting')},
            },
        ),
    ]
