# Generated by Django 5.1.4 on 2025-02-18 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0017_alertsettingotelupdate_alertsettingsyncstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettingotelupdate',
            name='value',
            field=models.IntegerField(help_text='Number of seconds', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10000)], verbose_name='Value'),
        ),
    ]
