# Generated by Django 5.1.4 on 2025-02-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0018_alter_alertsettingotelupdate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralertsettingotelupdate',
            name='moniker',
            field=models.CharField(default='', max_length=100, verbose_name='Bridge Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useralertsettingsyncstatus',
            name='moniker',
            field=models.CharField(default='', max_length=100, verbose_name='Bridge Name'),
            preserve_default=False,
        ),
    ]
