# Generated by Django 5.1.4 on 2025-02-20 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0019_useralertsettingotelupdate_moniker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettingsyncstatus',
            name='value',
            field=models.IntegerField(help_text='Number of blocks', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100000)], verbose_name='Value'),
        ),
    ]
