# Generated by Django 5.1.4 on 2025-02-20 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0020_alter_alertsettingsyncstatus_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettingotelupdate',
            name='value',
            field=models.IntegerField(help_text='Number of seconds', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(100000)], verbose_name='Value'),
        ),
    ]
