# Generated by Django 5.1.4 on 2025-02-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userphone_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('google', 'Google')], default='basic', max_length=10, verbose_name='Register type'),
        ),
    ]
