# Generated by Django 5.1.4 on 2025-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_register_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphone',
            name='is_tested_voice',
            field=models.BooleanField(default=False, verbose_name='Is tested Call'),
        ),
    ]
