# Generated by Django 5.1.4 on 2025-02-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userphone_is_tested_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phones_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total mumber of phones'),
        ),
    ]
