# Generated by Django 5.1.4 on 2025-01-31 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('users', '0002_userphone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('status', models.SlugField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='SENT', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sms', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_alert_setting_comission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_alert_setting_comission_sms', to='alerts.useralertsettingcomission', verbose_name='User Alert Setting Comission')),
                ('user_alert_setting_jailed_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_alert_setting_jailed_status_sms', to='alerts.useralertsettingjailedstatus', verbose_name='User Alert Setting Jailed Status')),
                ('user_alert_setting_tombstoned_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_alert_setting_tombstoned_status_sms', to='alerts.useralertsettingtombstonedstatus', verbose_name='User Alert Setting Tombstoned Status')),
                ('user_alert_setting_uptime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_alert_setting_uptime_sms', to='alerts.useralertsettinguptime', verbose_name='User Alert Setting Uptime')),
                ('user_alert_setting_voting_power', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_alert_setting_voting_power_sms', to='alerts.useralertsettingvotingpower', verbose_name='Voting Power Alert Settings')),
            ],
            options={
                'verbose_name': 'SMS Alert',
                'verbose_name_plural': 'SMS Alerts',
            },
        ),
        migrations.CreateModel(
            name='SMSConfirm',
            fields=[
                ('smsalert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.smsalert')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Confirmation Code')),
                ('expire_code', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Code expiration date')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
            ],
            options={
                'verbose_name': 'SMS Confirm',
                'verbose_name_plural': 'SMS Confirms',
            },
            bases=('sms.smsalert',),
        ),
    ]
