# Generated by Django 5.1.4 on 2025-01-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsalert',
            name='provider',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='sms_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID'),
        ),
        migrations.AddField(
            model_name='smsconfirm',
            name='provider',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AddField(
            model_name='smsconfirm',
            name='sms_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID'),
        ),
        migrations.AlterField(
            model_name='smsalert',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='SENT', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='smsconfirm',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='SENT', max_length=25, verbose_name='Status'),
        ),
    ]
