# Generated by Django 5.1.4 on 2025-02-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smsalert_provider_smsalert_sms_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsalert',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='smsconfirm',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
    ]
