# Generated by Django 5.1.4 on 2025-02-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_smsalert_provider_alter_smsconfirm_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsalert',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='smsconfirm',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Confirmation Code'),
        ),
        migrations.AlterField(
            model_name='smsconfirm',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status'),
        ),
    ]
