# Generated by Django 5.1.4 on 2025-02-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alter_alertsettingbondedstatus_options_and_more'),
        ('sms', '0005_smsalert_user_alert_setting_bonded_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsalert',
            name='user_alert_setting_bonded_status',
        ),
        migrations.RemoveField(
            model_name='smsalert',
            name='user_alert_setting_comission',
        ),
        migrations.RemoveField(
            model_name='smsalert',
            name='user_alert_setting_jailed_status',
        ),
        migrations.RemoveField(
            model_name='smsalert',
            name='user_alert_setting_tombstoned_status',
        ),
        migrations.RemoveField(
            model_name='smsalert',
            name='user_alert_setting_uptime',
        ),
        migrations.RemoveField(
            model_name='smsalert',
            name='user_alert_setting_voting_power',
        ),
        migrations.AddField(
            model_name='smsalert',
            name='alert_setting_bonded_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_bonded_status_sms', to='alerts.alertsettingbondedstatus', verbose_name='Bonded Status Alert Settings'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='alert_setting_comission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_comission_sms', to='alerts.alertsettingcomission', verbose_name='Comission Alert Settings'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='alert_setting_jailed_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_jailed_status_sms', to='alerts.alertsettingjailedstatus', verbose_name='Jailed Status Alert Setting'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='alert_setting_tombstoned_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_tombstoned_status_sms', to='alerts.alertsettingtombstonedstatus', verbose_name='Tombstoned Status Alert Settings'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='alert_setting_uptime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_uptime_sms', to='alerts.alertsettinguptime', verbose_name='Uptime Alert Settings'),
        ),
        migrations.AddField(
            model_name='smsalert',
            name='alert_setting_voting_power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_voting_power_sms', to='alerts.alertsettingvotingpower', verbose_name='Voting Power Alert Settings'),
        ),
    ]
