# Generated by Django 5.1.4 on 2025-02-10 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alter_alertsettingbondedstatus_template_decraease_and_more'),
        ('sms', '0006_remove_smsalert_user_alert_setting_bonded_status_and_more'),
        ('users', '0003_alter_userphone_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAlertBondedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='SMS Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_bonded_status_sms', to='alerts.alertsettingbondedstatus', verbose_name='Bond Status Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bond Status SMS Alert',
                'verbose_name_plural': 'Bond Status SMS Alerts',
            },
        ),
        migrations.CreateModel(
            name='SMSAlertComission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='SMS Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_comission_sms', to='alerts.alertsettingcomission', verbose_name='Comission Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comission SMS Alert',
                'verbose_name_plural': 'Comission SMS Alerts',
            },
        ),
        migrations.CreateModel(
            name='SMSAlertJailedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='SMS Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_jailed_status_sms', to='alerts.alertsettingjailedstatus', verbose_name='Jailed Alert Setting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Jailed SMS Alert',
                'verbose_name_plural': 'jailed SMS Alerts',
            },
        ),
        migrations.CreateModel(
            name='SMSAlertTombstonedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='SMS Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_tombstoned_status_sms', to='alerts.alertsettingtombstonedstatus', verbose_name='Tombstoned Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tombstoned SMS Alert',
                'verbose_name_plural': 'Tombstoned SMS Alerts',
            },
        ),
        migrations.CreateModel(
            name='SMSAlertUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='SMS Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_uptime_sms', to='alerts.alertsettinguptime', verbose_name='Uptime Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Uptime SMS Alert',
                'verbose_name_plural': 'Uptime SMS Alerts',
            },
        ),
        migrations.CreateModel(
            name='SMSAlertVotingPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], default='MAIN', max_length=25, verbose_name='SMS Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_voting_power_sms', to='alerts.alertsettingvotingpower', verbose_name='Voting Power Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Voting Power SMS Alert',
                'verbose_name_plural': 'Voting Power SMS Alerts',
            },
        ),
        migrations.DeleteModel(
            name='SMSAlert',
        ),
    ]
