# Generated by Django 5.1.4 on 2025-02-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_smsalertbondedstatus_smsalertcomission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsalertbondedstatus',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='smsalertcomission',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='smsalertjailedstatus',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='smsalerttombstonedstatus',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='smsalertuptime',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='smsalertvotingpower',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
        migrations.AddField(
            model_name='smsconfirm',
            name='is_resent',
            field=models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel'),
        ),
    ]
