# Generated by Django 5.1.4 on 2025-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_smsalertbondedstatus_is_resent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsalertbondedstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='smsalertbondedstatus',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='smsalertcomission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='smsalertcomission',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='smsalertjailedstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='smsalertjailedstatus',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='smsalerttombstonedstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='smsalerttombstonedstatus',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='smsalertuptime',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='smsalertuptime',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='smsalertvotingpower',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='smsalertvotingpower',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='smsconfirm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='smsconfirm',
            name='provider',
            field=models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider'),
        ),
    ]
