# Generated by Django 5.1.4 on 2025-02-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0017_alertsettingotelupdate_alertsettingsyncstatus_and_more'),
        ('sms', '0009_alter_smsalertbondedstatus_created_and_more'),
        ('users', '0003_alter_userphone_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAlertOtelUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('is_resent', models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_otel_update_sms', to='alerts.alertsettingotelupdate', verbose_name='Otel Update Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Otel Update SMS Alert',
                'verbose_name_plural': 'Otel Update SMS Alerts',
            },
        ),
        migrations.CreateModel(
            name='SMSAlertSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider SMS ID')),
                ('sent_text', models.TextField(verbose_name='SMS Text')),
                ('provider', models.CharField(choices=[('MAIN', 'Main (Hicell)'), ('RESERVE1', 'Reserve (Bird)')], db_index=True, default='MAIN', max_length=25, verbose_name='SMS Provider')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVRED', 'Undelivered'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], db_index=True, default='NEW', max_length=25, verbose_name='Status')),
                ('err', models.CharField(blank=True, max_length=256, null=True, verbose_name='Error Details')),
                ('is_resent', models.BooleanField(default=False, verbose_name='Is Resended via Reserved channel')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userphone', verbose_name='Phone Number')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_setting_sync_status_sms', to='alerts.alertsettingsyncstatus', verbose_name='Sync Status Alert Settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sync Status SMS Alert',
                'verbose_name_plural': 'Sync Status SMS Alerts',
            },
        ),
    ]
