# Generated by Django 5.1.4 on 2025-03-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0022_alter_blockchain_ntype'),
        ('sms', '0010_smsalertotelupdate_smsalertsyncstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsalertbondedstatus',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsalertbondedstatus',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='smsalertcomission',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsalertcomission',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='smsalertjailedstatus',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsalertjailedstatus',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='smsalertotelupdate',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsalertotelupdate',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='smsalertsyncstatus',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsalertsyncstatus',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='smsalerttombstonedstatus',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsalerttombstonedstatus',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='smsalertuptime',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsalertuptime',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='smsalertvotingpower',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsalertvotingpower',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
        migrations.AddField(
            model_name='smsconfirm',
            name='bridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainbridge', verbose_name='Bridge'),
        ),
        migrations.AddField(
            model_name='smsconfirm',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchains.blockchainvalidator', verbose_name='Validator'),
        ),
    ]
